processinf.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <signal.h>
*
#include <string.h>
*
Functions
void processInfo ()
void getInput (char word[])
char * revChars (char revword[])
char * upperCase (char upper[])
Function Documentation
void getInput (char word[])
Definition at line 13 of file processinf.c.
Referenced by main().
{
fputs("Enter up to ten characters: ", stdout);
fflush(stdout);
if(fgets(word, sizeof word, stdin) != NULL)
{
char *newline = strchr(word, '\n');
if(newline != NULL)
{
*newline = '\0';
}
}
}
void processInfo ()
Definition at line 7 of file processinf.c.
 {
 printf("Parent is: %d...\n",getppid());
 printf("Fork running is: %d...\n",getpid());
 }
char* revChars (char revword[])
Definition at line 27 of file processinf.c.
Referenced by processTwo().
                              {
int ten = 0;
int flip = strlen(revword);
int loopr = flip + 1;
static char newWord[10] = {0};
for(ten = 0; ten < loopr; ten++){
flip--;
newWord[flip] = revword[ten];
}
return newWord;
}
char* upperCase (char upper[])
Definition at line 39 of file processinf.c.
Referenced by processThree().
{
int ten = 0;
int len = strlen(upper);
for(ten = 0; ten < len; ten++){
upper[ten] = toupper(upper[ten]);
}
return upper;
}