psthreads.c File Reference
#include <signal.h>
*
#include `processinf.h`
*
Macros
#define READ 0
#define WRITE 1
Functions
void processOne (int *fd1, char word[])
void processTwo (int *fd1, int *fd2)
void processThree (int *fd2, int *fd3)
void processFin (int *fd3, int *fd1)
Macro Definition Documentation
#define READ 0
Definition at line 4 of file psthreads.c.
Referenced by processFin(), processOne(), processThree(), and processTwo().
#define WRITE 1
Definition at line 5 of file psthreads.c.
Referenced by processFin(), processOne(), processThree(), and processTwo().
Function Documentation
void processFin (int * fd3, int * fd1)
read pipe three and close the end of pipes back at fd1
Definition at line 55 of file psthreads.c.
Referenced by main().
                                  {
int recieved;
static char message[10];
static char up[10];
close(fd3[WRITE]);
recieved = read(fd3[READ], message, 100);
if(recieved){
printf("\nEnd of Pipes: %s\n\n", message);
}
close(fd3[READ]);
close(fd1[READ]);
sleep(2);
write(fd1[WRITE],up,strlen(up) + 1);
sleep(1);
close(fd1[WRITE]);
}
void processOne (int * fd1, char word[])
uncomment the printfs below for more verbous output write of pipe one
Definition at line 9 of file psthreads.c.
Referenced by main().
                                      {
close(fd1[READ]);
sleep(2);
write(fd1[WRITE],word,strlen(word) + 1);
sleep(1);
close(fd1[WRITE]);
}
void processThree (int * fd2, int * fd3)
read of pipe two and write to pipe three
Definition at line 36 of file psthreads.c.
Referenced by main().
                                    {
int recieved;
static char message[10];
static char up[10];
close(fd2[WRITE]);
recieved = read(fd2[READ], message, 100);
if(recieved){
//printf("\nProcess Three: %s\n\n", message);
strcpy(up,upperCase(message));
//printf("Set characters to uppercase: %s\n\n", up);
}
close(fd2[READ]);
close(fd3[READ]);
sleep(2);
write(fd3[WRITE],up,strlen(up) + 1);
sleep(1);
close(fd3[WRITE]);
}
void processTwo (int * fd1, int * fd2)
read pipe one and write pipetwo
Definition at line 17 of file psthreads.c.
Referenced by main().
                                  {
int recieved;
static char message[10];
static char nmessage[10];
close(fd1[WRITE]);
recieved = read(fd1[READ], message, 100);
if(recieved){
//printf("\nProcess Two: %s\n\n", message);
strcpy(nmessage,revChars(message));
//printf("Reversed to: %s\n\n", nmessage);
}
close(fd1[READ]);
close(fd2[READ]);
sleep(2);
write(fd2[WRITE],nmessage,strlen(nmessage) + 1);
sleep(1);
close(fd2[WRITE]);
}